<a href="https://colab.research.google.com/github/hitanshu319/machine-learning/blob/master/numpyday1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([2,7,1,99,4])
type(a)

numpy.ndarray

In [3]:
import numpy as np
b=np.array([12,17 ,11,199,14])
type(b)

numpy.ndarray

In [4]:
type(a)

numpy.ndarray

In [5]:
a[0]

2

In [6]:
b[0]





12

In [7]:
a+b



array([ 14,  24,  12, 298,  18])

In [8]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
c=a+b

In [10]:
c

array([ 14,  24,  12, 298,  18])

In [0]:
m=a*b

In [12]:
m

array([   24,   119,    11, 19701,    56])

In [0]:
a5=a+5


In [14]:
a5

array([  7,  12,   6, 104,   9])

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [16]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [17]:
x[0]

array([2, 5, 8])

In [19]:
x[0][1]

5

In [20]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x+7

In [22]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [23]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [24]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [0]:
z=np.array([[2,7],[3,8],[2,9],[9,4]])

In [26]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [27]:
x


array([[2, 5, 8],
       [3, 6, 1]])

In [28]:
x.shape

(2, 3)

In [29]:
z.shape


(4, 2)

In [30]:
z[0:2]

array([[2, 7],
       [3, 8]])

In [32]:
z[0:,0:2]

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [33]:
z[0:,0]

array([2, 3, 2, 9])

In [34]:
z[0:2,0]

array([2, 3])

In [35]:
z[0:,1]

array([7, 8, 9, 4])

In [36]:
z[0:,0:1]

array([[2],
       [3],
       [2],
       [9]])

In [37]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [38]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [39]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [40]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [41]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [42]:
z[0:4:2]

array([[2, 7],
       [2, 9]])

In [43]:
z[0,2]

IndexError: ignored

In [44]:
z[[0,2]]

array([[2, 7],
       [2, 9]])

In [45]:
z[0:,[0,3]]

IndexError: ignored

In [48]:
z[[0,3],1]

array([7, 4])

In [47]:
z

array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [0]:
b=np.array([[1,9,7],[3,2,8],[4,5,6,],[2,9,0]])

In [51]:
b

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [53]:
b[0:,1]

array([9, 2, 5, 9])

In [55]:
b[[0,3],[0,1]]

array([1, 9])

In [56]:
b[1:,2]

array([8, 6, 0])

In [57]:
b[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [58]:
x




array([[2, 5, 8],
       [3, 6, 1]])

In [59]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [61]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])